import json
from qdrant_client import QdrantClient

def show_embeddings():
    client = QdrantClient(url="http://localhost:6333")
    collection_name = "elara_global_v2"
    
    records, next_page = client.scroll(
        collection_name=collection_name,
        limit=9,
        with_payload=True,
        with_vectors=True
    )
    
    markdown_output = "# Vector Embeddings Sample\n\n"
    markdown_output += "Here are the exact semantic vectors generated by the AI for your codebase.\n\n"
    
    for record in records:
        payload = record.payload
        markdown_output += f"### Payload Keys: {list(payload.keys())}\n"
        
        file_path = payload.get("filepath", "Unknown file")  # Maybe it's filepath?
        if file_path == "Unknown file":
            file_path = payload.get("path", "Unknown file")
            
        symbol = payload.get("symbol_name", "Unknown symbol")
        if symbol == "Unknown symbol":
            symbol = payload.get("name", "Unknown symbol")
            
        vector = record.vector
        vec_preview = f"[{vector[0]:.4f}, {vector[1]:.4f}, {vector[2]:.4f}, ..., {vector[-2]:.4f}, {vector[-1]:.4f}]"
        
        markdown_output += f"### {symbol}\n"
        markdown_output += f"- **File**: `{file_path}`\n"
        markdown_output += f"- **Dimensions**: {len(vector)}\n"
        markdown_output += f"- **Vector Preview**: `{vec_preview}`\n"
        
        text_content = payload.get("content", payload.get("text", payload.get("code", "")))
        if text_content:
            code_snippet = text_content[:150].replace("\n", " ") + "..."
            markdown_output += f"```javascript\n{code_snippet}\n```\n"
        markdown_output += "\n"
        
    print(markdown_output)

if __name__ == "__main__":
    show_embeddings()
