"""Make workspace_id nullable in activity_logs

Revision ID: 00051fd19c96
Revises: 4c5094b455c1
Create Date: 2026-08-06 12:33:37.833104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00051fd19c96'
down_revision: Union[str, Sequence[str], None] = '4c5094b455c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'activity_logs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.alter_column('activity_logs', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
