"""Add join request fields

Revision ID: 0c6e1bfb8dbe
Revises: 8971d55843cc
Create Date: 2026-08-10 21:56:57.469021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6e1bfb8dbe'
down_revision: Union[str, Sequence[str], None] = '8971d55843cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_join_requests',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='joinrequeststatus'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_join_requests_organization_id'), 'organization_join_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_join_requests_user_id'), 'organization_join_requests', ['user_id'], unique=False)
    join_policy = sa.Enum('CLOSED', 'REQUEST_TO_JOIN', 'OPEN', name='joinpolicy')
    join_policy.create(op.get_bind(), checkfirst=True)
    op.add_column('organizations', sa.Column('discoverable', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('organizations', sa.Column('join_policy', join_policy, server_default='CLOSED', nullable=False))
    op.add_column('organizations', sa.Column('tagline', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'tagline')
    op.drop_column('organizations', 'join_policy')
    op.drop_column('organizations', 'discoverable')
    op.drop_index(op.f('ix_organization_join_requests_user_id'), table_name='organization_join_requests')
    op.drop_index(op.f('ix_organization_join_requests_organization_id'), table_name='organization_join_requests')
    op.drop_table('organization_join_requests')
    # ### end Alembic commands ###
