"""phase_5_profiles_and_preferences

Revision ID: 258f8f40383c
Revises: 4d52c6d3297c
Create Date: 2026-08-06 13:50:19.649844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '258f8f40383c'
down_revision: Union[str, Sequence[str], None] = '4d52c6d3297c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_onboarding',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('google_connected', sa.Boolean(), nullable=False),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.Column('github_connected', sa.Boolean(), nullable=False),
    sa.Column('repository_connected', sa.Boolean(), nullable=False),
    sa.Column('first_ai_scan', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_onboarding_user_id'), 'user_onboarding', ['user_id'], unique=True)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('color_scheme', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('sidebar_collapsed', sa.Boolean(), nullable=False),
    sa.Column('density', sa.String(), nullable=True),
    sa.Column('default_workspace', sa.UUID(), nullable=True),
    sa.Column('default_dashboard', sa.String(), nullable=True),
    sa.Column('default_repository', sa.UUID(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dashboard_layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('command_palette_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['default_repository'], ['repositories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_workspace'], ['workspaces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.add_column('developer_profiles', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('developer_profiles', sa.Column('company', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('organization', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('current_company', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('current_position', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('developer_profiles', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('location', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('primary_language', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('preferred_languages', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('developer_profiles', sa.Column('frameworks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('developer_profiles', sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('developer_profiles', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('portfolio_url', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('website', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('profile_completion_percentage', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('developer_profiles', sa.Column('available_for_assignment', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('developer_profiles', sa.Column('open_to_collaboration', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.alter_column('developer_profiles', 'github_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('developer_profiles', 'availability',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               nullable=True)
    op.drop_index('ix_developer_profiles_member_id', table_name='developer_profiles')
    op.drop_index('ix_developer_profiles_workspace_id', table_name='developer_profiles')
    op.create_index(op.f('ix_developer_profiles_user_id'), 'developer_profiles', ['user_id'], unique=True)
    op.drop_constraint('developer_profiles_member_id_fkey', 'developer_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'developer_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('developer_profiles', 'workspace_id')
    op.drop_column('developer_profiles', 'member_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer_profiles', sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('developer_profiles', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'developer_profiles', type_='foreignkey')
    op.create_foreign_key('developer_profiles_member_id_fkey', 'developer_profiles', 'workspace_members', ['member_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_developer_profiles_user_id'), table_name='developer_profiles')
    op.create_index('ix_developer_profiles_workspace_id', 'developer_profiles', ['workspace_id'], unique=False)
    op.create_index('ix_developer_profiles_member_id', 'developer_profiles', ['member_id'], unique=False)
    op.alter_column('developer_profiles', 'availability',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('developer_profiles', 'github_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('developer_profiles', 'open_to_collaboration')
    op.drop_column('developer_profiles', 'available_for_assignment')
    op.drop_column('developer_profiles', 'profile_completion_percentage')
    op.drop_column('developer_profiles', 'website')
    op.drop_column('developer_profiles', 'portfolio_url')
    op.drop_column('developer_profiles', 'linkedin_url')
    op.drop_column('developer_profiles', 'certifications')
    op.drop_column('developer_profiles', 'frameworks')
    op.drop_column('developer_profiles', 'tech_stack')
    op.drop_column('developer_profiles', 'preferred_languages')
    op.drop_column('developer_profiles', 'primary_language')
    op.drop_column('developer_profiles', 'timezone')
    op.drop_column('developer_profiles', 'location')
    op.drop_column('developer_profiles', 'bio')
    op.drop_column('developer_profiles', 'experience_years')
    op.drop_column('developer_profiles', 'current_position')
    op.drop_column('developer_profiles', 'current_company')
    op.drop_column('developer_profiles', 'designation')
    op.drop_column('developer_profiles', 'organization')
    op.drop_column('developer_profiles', 'company')
    op.drop_column('developer_profiles', 'user_id')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_onboarding_user_id'), table_name='user_onboarding')
    op.drop_table('user_onboarding')
    # ### end Alembic commands ###
