"""phase_4_session_enhancements

Revision ID: 4d52c6d3297c
Revises: fd036e312b18
Create Date: 2026-08-06 13:45:26.476962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d52c6d3297c'
down_revision: Union[str, Sequence[str], None] = 'fd036e312b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('refresh_token_version', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.add_column('user_sessions', sa.Column('device_type', sa.String(), nullable=True))
    op.add_column('user_sessions', sa.Column('device_name', sa.String(), nullable=True))
    op.add_column('user_sessions', sa.Column('browser', sa.String(), nullable=True))
    op.add_column('user_sessions', sa.Column('operating_system', sa.String(), nullable=True))
    op.add_column('user_sessions', sa.Column('city', sa.String(), nullable=True))
    op.add_column('user_sessions', sa.Column('country', sa.String(), nullable=True))
    op.add_column('user_sessions', sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_sessions', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'revoked_at')
    op.drop_column('user_sessions', 'last_activity')
    op.drop_column('user_sessions', 'country')
    op.drop_column('user_sessions', 'city')
    op.drop_column('user_sessions', 'operating_system')
    op.drop_column('user_sessions', 'browser')
    op.drop_column('user_sessions', 'device_name')
    op.drop_column('user_sessions', 'device_type')
    op.drop_column('user_sessions', 'refresh_token_version')
    # ### end Alembic commands ###
