"""enterprise_profile_fields_refined

Revision ID: 4e2754029077
Revises: ddfc03fd6f9a
Create Date: 2026-08-06 15:21:13.352950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e2754029077'
down_revision: Union[str, Sequence[str], None] = 'ddfc03fd6f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer_profiles', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('username', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('primary_role', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('databases', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('developer_profiles', sa.Column('cloud_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('developer_profiles', sa.Column('devops_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('developer_profiles', sa.Column('ai_ml_technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('developer_profiles', sa.Column('areas_of_expertise', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('developer_profiles', sa.Column('twitter_username', sa.String(), nullable=True))
    op.drop_column('developer_profiles', 'profile_completion_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer_profiles', sa.Column('profile_completion_percentage', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('developer_profiles', 'twitter_username')
    op.drop_column('developer_profiles', 'areas_of_expertise')
    op.drop_column('developer_profiles', 'ai_ml_technologies')
    op.drop_column('developer_profiles', 'devops_tools')
    op.drop_column('developer_profiles', 'cloud_platforms')
    op.drop_column('developer_profiles', 'databases')
    op.drop_column('developer_profiles', 'primary_role')
    op.drop_column('developer_profiles', 'username')
    op.drop_column('developer_profiles', 'display_name')
    op.drop_column('developer_profiles', 'last_name')
    op.drop_column('developer_profiles', 'first_name')
    # ### end Alembic commands ###
