"""phase_x_github_profile_integration

Revision ID: 5208a9ffe11f
Revises: 4e2754029077
Create Date: 2026-08-06 18:59:26.005877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5208a9ffe11f'
down_revision: Union[str, Sequence[str], None] = '4e2754029077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer_profiles', sa.Column('github_user_id', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('github_avatar_url', sa.String(), nullable=True))
    op.add_column('developer_profiles', sa.Column('github_public_repos', sa.Integer(), nullable=True))
    op.add_column('developer_profiles', sa.Column('github_profile_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developer_profiles', 'github_profile_url')
    op.drop_column('developer_profiles', 'github_public_repos')
    op.drop_column('developer_profiles', 'github_avatar_url')
    op.drop_column('developer_profiles', 'github_user_id')
    # ### end Alembic commands ###
