"""bug_intake_complete

Revision ID: 6696b9dd6fb6
Revises: 702e5a16242e
Create Date: 2026-08-26 20:08:08.201963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6696b9dd6fb6'
down_revision: Union[str, Sequence[str], None] = '702e5a16242e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_assignments',
    sa.Column('bug_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['developer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_assignments_bug_id'), 'bug_assignments', ['bug_id'], unique=False)
    op.create_index(op.f('ix_bug_assignments_developer_id'), 'bug_assignments', ['developer_id'], unique=False)
    op.create_index(op.f('ix_bug_assignments_organization_id'), 'bug_assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bug_assignments_workspace_id'), 'bug_assignments', ['workspace_id'], unique=False)
    op.create_table('bug_comments',
    sa.Column('bug_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_comments_bug_id'), 'bug_comments', ['bug_id'], unique=False)
    op.create_index(op.f('ix_bug_comments_organization_id'), 'bug_comments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bug_comments_workspace_id'), 'bug_comments', ['workspace_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('request_hash', sa.String(), nullable=False),
    sa.Column('bug_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_organization_id'), 'idempotency_keys', ['organization_id'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_workspace_id'), 'idempotency_keys', ['workspace_id'], unique=False)
    op.add_column('bugs', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('bugs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('bugs', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bugs', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bugs', 'priority',
               existing_type=postgresql.ENUM('P0', 'P1', 'P2', 'P3', 'P4', name='bugpriority'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bugs', 'priority',
               existing_type=postgresql.ENUM('P0', 'P1', 'P2', 'P3', 'P4', name='bugpriority'),
               nullable=True)
    op.alter_column('bugs', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('bugs', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('bugs', 'deleted_at')
    op.drop_column('bugs', 'is_deleted')
    op.drop_index(op.f('ix_idempotency_keys_workspace_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_organization_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_bug_comments_workspace_id'), table_name='bug_comments')
    op.drop_index(op.f('ix_bug_comments_organization_id'), table_name='bug_comments')
    op.drop_index(op.f('ix_bug_comments_bug_id'), table_name='bug_comments')
    op.drop_table('bug_comments')
    op.drop_index(op.f('ix_bug_assignments_workspace_id'), table_name='bug_assignments')
    op.drop_index(op.f('ix_bug_assignments_organization_id'), table_name='bug_assignments')
    op.drop_index(op.f('ix_bug_assignments_developer_id'), table_name='bug_assignments')
    op.drop_index(op.f('ix_bug_assignments_bug_id'), table_name='bug_assignments')
    op.drop_table('bug_assignments')
    # ### end Alembic commands ###
