"""add_deleting_to_organizationstatus

Revision ID: 6e65a3f2f28b
Revises: e2362bc6b383
Create Date: 2026-08-24 22:49:17.694194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e65a3f2f28b'
down_revision: Union[str, Sequence[str], None] = 'e2362bc6b383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE organizationstatus ADD VALUE IF NOT EXISTS 'DELETING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing a value from a PostgreSQL ENUM is not natively supported 
    # without recreating the type and rewriting the column.
    pass
    # ### end Alembic commands ###
