"""Zero destruction bug intake

Revision ID: 702e5a16242e
Revises: 6e65a3f2f28b
Create Date: 2026-08-26 17:22:45.849531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '702e5a16242e'
down_revision: Union[str, Sequence[str], None] = '6e65a3f2f28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_api_keys',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_api_keys_key_hash'), 'workspace_api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_workspace_api_keys_organization_id'), 'workspace_api_keys', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workspace_api_keys_workspace_id'), 'workspace_api_keys', ['workspace_id'], unique=False)
    bugpriority = postgresql.ENUM('P0', 'P1', 'P2', 'P3', 'P4', name='bugpriority')
    bugpriority.create(op.get_bind(), checkfirst=True)
    
    op.add_column('bugs', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('bugs', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.add_column('bugs', sa.Column('repository_id', sa.UUID(), nullable=True))
    op.add_column('bugs', sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', 'P4', name='bugpriority'), nullable=True))
    op.add_column('bugs', sa.Column('environment', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bugs', sa.Column('reproduction_steps', sa.Text(), nullable=True))
    op.add_column('bugs', sa.Column('expected_behavior', sa.Text(), nullable=True))
    op.add_column('bugs', sa.Column('actual_behavior', sa.Text(), nullable=True))
    op.add_column('bugs', sa.Column('reporter_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bugs', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('bugs', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_bugs_organization_id'), 'bugs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bugs_repository_id'), 'bugs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_bugs_workspace_id'), 'bugs', ['workspace_id'], unique=False)
    op.drop_constraint('bugs_project_id_fkey', 'bugs', type_='foreignkey')
    op.create_foreign_key(None, 'bugs', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'bugs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bugs', 'repositories', ['repository_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'bugs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('workspaces', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'workspaces', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.drop_column('workspaces', 'organization_id')
    op.drop_constraint(None, 'bugs', type_='foreignkey')
    op.drop_constraint(None, 'bugs', type_='foreignkey')
    op.drop_constraint(None, 'bugs', type_='foreignkey')
    op.drop_constraint(None, 'bugs', type_='foreignkey')
    op.create_foreign_key('bugs_project_id_fkey', 'bugs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bugs_workspace_id'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_repository_id'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_organization_id'), table_name='bugs')
    op.alter_column('bugs', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('bugs', 'closed_at')
    op.drop_column('bugs', 'reporter_metadata')
    op.drop_column('bugs', 'actual_behavior')
    op.drop_column('bugs', 'expected_behavior')
    op.drop_column('bugs', 'reproduction_steps')
    op.drop_column('bugs', 'environment')
    op.drop_column('bugs', 'priority')
    op.drop_column('bugs', 'repository_id')
    op.drop_column('bugs', 'workspace_id')
    op.drop_column('bugs', 'organization_id')
    op.drop_index(op.f('ix_workspace_api_keys_workspace_id'), table_name='workspace_api_keys')
    op.drop_index(op.f('ix_workspace_api_keys_organization_id'), table_name='workspace_api_keys')
    op.drop_index(op.f('ix_workspace_api_keys_key_hash'), table_name='workspace_api_keys')
    op.drop_table('workspace_api_keys')
    
    bugpriority = postgresql.ENUM('P0', 'P1', 'P2', 'P3', 'P4', name='bugpriority')
    bugpriority.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
