"""phase_omega_step_2_saas

Revision ID: 726edb5aa896
Revises: 2835547e8970
Create Date: 2026-08-08 17:20:38.320066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726edb5aa896'
down_revision: Union[str, Sequence[str], None] = '2835547e8970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.drop_index('ix_api_keys_workspace_id', table_name='api_keys')
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.create_foreign_key('api_keys_organization_id_fkey', 'api_keys', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('api_keys', 'workspace_id')
    op.drop_index('ix_bug_attachments_workspace_id', table_name='bug_attachments')
    op.drop_column('bug_attachments', 'workspace_id')
    op.drop_index('ix_bugs_workspace_id', table_name='bugs')
    op.drop_column('bugs', 'workspace_id')
    op.add_column('projects', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.drop_index('ix_projects_workspace_id', table_name='projects')
    op.drop_constraint('uix_workspace_project_name', 'projects', type_='unique')
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_unique_constraint('uix_organization_project_name', 'projects', ['organization_id', 'name'])
    op.create_foreign_key('projects_organization_id_fkey', 'projects', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projects', 'workspace_id')
    op.drop_index('ix_repo_index_jobs_workspace_id', table_name='repo_index_jobs')
    op.drop_column('repo_index_jobs', 'workspace_id')
    op.add_column('repositories', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('repositories', sa.Column('provider_repository_id', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('github_installation_id', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('visibility', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('language', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('is_private', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_repositories_organization_id'), 'repositories', ['organization_id'], unique=False)
    op.create_unique_constraint('uix_organization_repo_extid', 'repositories', ['organization_id', 'external_id'])
    op.create_unique_constraint('uix_organization_repo_fullname', 'repositories', ['organization_id', 'full_name'])
    op.create_foreign_key('repositories_organization_id_fkey', 'repositories', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('repositories_workspace_id_fkey', 'repositories', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint('chk_repo_owner', 'repositories', '(workspace_id IS NULL) <> (organization_id IS NULL)')
    op.drop_index('ix_team_members_workspace_id', table_name='team_members')
    op.drop_column('team_members', 'workspace_id')
    op.add_column('teams', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.drop_index('ix_teams_workspace_id', table_name='teams')
    op.create_index(op.f('ix_teams_organization_id'), 'teams', ['organization_id'], unique=False)
    op.create_unique_constraint('uix_organization_team_name', 'teams', ['organization_id', 'name'])
    op.create_foreign_key('teams_organization_id_fkey', 'teams', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('teams', 'workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('teams_organization_id_fkey', 'teams', type_='foreignkey')
    op.drop_constraint('uix_organization_team_name', 'teams', type_='unique')
    op.drop_index(op.f('ix_teams_organization_id'), table_name='teams')
    op.create_index('ix_teams_workspace_id', 'teams', ['workspace_id'], unique=False)
    op.drop_column('teams', 'organization_id')
    op.add_column('team_members', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index('ix_team_members_workspace_id', 'team_members', ['workspace_id'], unique=False)
    op.drop_constraint('chk_repo_owner', 'repositories', type_='check')
    op.drop_constraint('repositories_workspace_id_fkey', 'repositories', type_='foreignkey')
    op.drop_constraint('repositories_organization_id_fkey', 'repositories', type_='foreignkey')
    op.drop_constraint('uix_organization_repo_fullname', 'repositories', type_='unique')
    op.drop_constraint('uix_organization_repo_extid', 'repositories', type_='unique')
    op.drop_index(op.f('ix_repositories_organization_id'), table_name='repositories')
    op.drop_column('repositories', 'is_private')
    op.drop_column('repositories', 'language')
    op.drop_column('repositories', 'visibility')
    op.drop_column('repositories', 'github_installation_id')
    op.drop_column('repositories', 'provider_repository_id')
    op.drop_column('repositories', 'organization_id')
    op.add_column('repo_index_jobs', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index('ix_repo_index_jobs_workspace_id', 'repo_index_jobs', ['workspace_id'], unique=False)
    op.add_column('projects', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('projects_organization_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('uix_organization_project_name', 'projects', type_='unique')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.create_unique_constraint('uix_workspace_project_name', 'projects', ['workspace_id', 'name'])
    op.create_index('ix_projects_workspace_id', 'projects', ['workspace_id'], unique=False)
    op.drop_column('projects', 'organization_id')
    op.add_column('bugs', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index('ix_bugs_workspace_id', 'bugs', ['workspace_id'], unique=False)
    op.add_column('bug_attachments', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index('ix_bug_attachments_workspace_id', 'bug_attachments', ['workspace_id'], unique=False)
    op.add_column('api_keys', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('api_keys_organization_id_fkey', 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.create_index('ix_api_keys_workspace_id', 'api_keys', ['workspace_id'], unique=False)
    op.drop_column('api_keys', 'organization_id')
    # ### end Alembic commands ###
