"""Add unique constraint for idempotency keys

Revision ID: 732c1c6ed714
Revises: 6696b9dd6fb6
Create Date: 2026-08-27 17:26:43.193586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732c1c6ed714'
down_revision: Union[str, Sequence[str], None] = '6696b9dd6fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_workspace_id_key', 'idempotency_keys', ['workspace_id', 'key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_workspace_id_key', 'idempotency_keys', type_='unique')
    # ### end Alembic commands ###
