"""Add enterprise repository fields

Revision ID: 8971d55843cc
Revises: 9a1c8649f163
Create Date: 2026-08-10 20:32:21.525825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8971d55843cc'
down_revision: Union[str, Sequence[str], None] = '9a1c8649f163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('clone_url', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('html_url', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('last_push_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('repositories', sa.Column('repository_size', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('stars', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('forks', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('open_issues', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('archived', sa.Boolean(), nullable=False))
    op.add_column('repositories', sa.Column('disabled', sa.Boolean(), nullable=False))
    op.add_column('repositories', sa.Column('index_status', sa.String(), nullable=False))
    op.add_column('repositories', sa.Column('ai_ready', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'ai_ready')
    op.drop_column('repositories', 'index_status')
    op.drop_column('repositories', 'disabled')
    op.drop_column('repositories', 'archived')
    op.drop_column('repositories', 'open_issues')
    op.drop_column('repositories', 'forks')
    op.drop_column('repositories', 'stars')
    op.drop_column('repositories', 'repository_size')
    op.drop_column('repositories', 'last_push_at')
    op.drop_column('repositories', 'html_url')
    op.drop_column('repositories', 'clone_url')
    op.drop_column('repositories', 'owner')
    # ### end Alembic commands ###
