"""Add bug_id, org_id, metadata to ActivityLog

Revision ID: 8e1427331d35
Revises: e46924abc379
Create Date: 2026-08-27 20:20:59.428962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1427331d35'
down_revision: Union[str, Sequence[str], None] = 'e46924abc379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
