"""phase_omega_step3_org_settings

Revision ID: 9a1c8649f163
Revises: 726edb5aa896
Create Date: 2026-08-10 15:33:56.371807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a1c8649f163'
down_revision: Union[str, Sequence[str], None] = '726edb5aa896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_invitations', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization_settings', sa.Column('allowed_login_providers', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='["EMAIL", "GITHUB", "GOOGLE"]'))
    op.add_column('organization_settings', sa.Column('session_timeout_minutes', sa.Integer(), nullable=False, server_default='1440'))
    op.add_column('organization_settings', sa.Column('embedding_provider', sa.String(), nullable=False, server_default='OPENAI'))
    op.add_column('organization_settings', sa.Column('llm_provider', sa.String(), nullable=False, server_default='OPENAI'))
    op.add_column('organization_settings', sa.Column('ai_defaults', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('organization_settings', sa.Column('default_repository_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('organization_settings', sa.Column('default_branch', sa.String(), nullable=False, server_default='main'))
    op.add_column('organization_settings', sa.Column('github_integration_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('organization_settings', sa.Column('gitlab_integration_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('organization_settings', sa.Column('azure_devops_integration_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('organizations', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'website')
    op.drop_column('organization_settings', 'azure_devops_integration_enabled')
    op.drop_column('organization_settings', 'gitlab_integration_enabled')
    op.drop_column('organization_settings', 'github_integration_enabled')
    op.drop_column('organization_settings', 'default_branch')
    op.drop_column('organization_settings', 'default_repository_settings')
    op.drop_column('organization_settings', 'ai_defaults')
    op.drop_column('organization_settings', 'llm_provider')
    op.drop_column('organization_settings', 'embedding_provider')
    op.drop_column('organization_settings', 'session_timeout_minutes')
    op.drop_column('organization_settings', 'allowed_login_providers')
    op.drop_column('organization_invitations', 'revoked_at')
    # ### end Alembic commands ###
