"""oauth unique constraints

Revision ID: a33be732ab8d
Revises: 098aaad2b3e0
Create Date: 2026-08-08 13:37:29.510806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33be732ab8d'
down_revision: Union[str, Sequence[str], None] = '098aaad2b3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_oauth_provider_user_id', 'oauth_accounts', ['provider', 'provider_user_id'])
    op.create_unique_constraint('uq_oauth_user_id_provider', 'oauth_accounts', ['user_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_oauth_user_id_provider', 'oauth_accounts', type_='unique')
    op.drop_constraint('uq_oauth_provider_user_id', 'oauth_accounts', type_='unique')
    # ### end Alembic commands ###
