"""Add enterprise notifications

Revision ID: a3a21c4f64a9
Revises: 0c6e1bfb8dbe
Create Date: 2026-08-14 11:42:25.727982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3a21c4f64a9'
down_revision: Union[str, Sequence[str], None] = '0c6e1bfb8dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enums explicitly for Postgres
    notification_priority = postgresql.ENUM('CRITICAL', 'WARNING', 'INFO', 'SUCCESS', name='notificationpriority')
    notification_priority.create(op.get_bind(), checkfirst=True)
    
    notification_type = postgresql.ENUM('JOIN_REQUEST', 'JOIN_APPROVED', 'JOIN_REJECTED', 'ORGANIZATION_INVITATION', 'ROLE_CHANGED', 'PROJECT_INVITED', 'PROJECT_CREATED', 'REPOSITORY_CONNECTED', 'REPOSITORY_SYNC_FAILED', 'BUG_ASSIGNED', 'BUG_STATUS_CHANGED', 'BUG_COMMENT', 'BUG_MENTION', 'AI_ANALYSIS_COMPLETED', 'AI_ANALYSIS_FAILED', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'SUBSCRIPTION_RENEWED', 'SUBSCRIPTION_EXPIRING', 'USAGE_LIMIT_REACHED', 'SYSTEM_ALERT', 'SECURITY_ALERT', 'ANNOUNCEMENT', name='notificationtype')
    notification_type.create(op.get_bind(), checkfirst=True)
    
    # We drop the old type column and add it again to avoid complex type casting in PG
    op.drop_column('notifications', 'type')
    op.add_column('notifications', sa.Column('type', notification_type, nullable=False, server_default='SYSTEM_ALERT'))

    op.add_column('notifications', sa.Column('recipient_user_id', sa.UUID(), nullable=False))
    op.add_column('notifications', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('priority', notification_priority, nullable=False, server_default='INFO'))
    op.add_column('notifications', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('notifications', sa.Column('message', sa.String(length=1024), nullable=False))
    op.add_column('notifications', sa.Column('action_url', sa.String(length=512), nullable=True))
    op.add_column('notifications', sa.Column('action_label', sa.String(length=100), nullable=True))
    op.add_column('notifications', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))

    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_workspace_id', table_name='notifications')
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'users', ['recipient_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'workspace_id')
    op.drop_column('notifications', 'channel')
    op.drop_column('notifications', 'payload')
    op.drop_column('notifications', 'user_id')
    op.drop_column('notifications', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('status', postgresql.ENUM('PENDING', 'SENT', 'FAILED', 'READ', name='notifstatus'), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('channel', postgresql.ENUM('EMAIL', 'IN_APP', 'SLACK', name='notifchannel'), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.create_index('ix_notifications_workspace_id', 'notifications', ['workspace_id'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('JOIN_REQUEST', 'JOIN_APPROVED', 'JOIN_REJECTED', 'ORGANIZATION_INVITATION', 'ROLE_CHANGED', 'PROJECT_INVITED', 'PROJECT_CREATED', 'REPOSITORY_CONNECTED', 'REPOSITORY_SYNC_FAILED', 'BUG_ASSIGNED', 'BUG_STATUS_CHANGED', 'BUG_COMMENT', 'BUG_MENTION', 'AI_ANALYSIS_COMPLETED', 'AI_ANALYSIS_FAILED', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'SUBSCRIPTION_RENEWED', 'SUBSCRIPTION_EXPIRING', 'USAGE_LIMIT_REACHED', 'SYSTEM_ALERT', 'SECURITY_ALERT', 'ANNOUNCEMENT', name='notificationtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'metadata')
    op.drop_column('notifications', 'action_label')
    op.drop_column('notifications', 'action_url')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'priority')
    op.drop_column('notifications', 'organization_id')
    op.drop_column('notifications', 'recipient_user_id')
    # ### end Alembic commands ###
