"""phase_2_remove_auth_provider

Revision ID: abde83a72db0
Revises: c3cf2f78e625
Create Date: 2026-08-06 13:43:41.015874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abde83a72db0'
down_revision: Union[str, Sequence[str], None] = 'c3cf2f78e625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
