"""Add GitHubIntegration model

Revision ID: b02c94ec8ada
Revises: fa077bb892d5
Create Date: 2026-08-18 17:28:05.733296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02c94ec8ada'
down_revision: Union[str, Sequence[str], None] = 'fa077bb892d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_integrations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('github_installation_id', sa.String(), nullable=True),
    sa.Column('github_account_id', sa.String(), nullable=True),
    sa.Column('github_account_login', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'REVOKED', 'ERROR', name='integrationstatus'), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'provider', name='uix_organization_provider')
    )
    op.create_index(op.f('ix_github_integrations_organization_id'), 'github_integrations', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_integrations_organization_id'), table_name='github_integrations')
    op.drop_table('github_integrations')
    # ### end Alembic commands ###
