"""phase_1_safe_alterations

Revision ID: c3cf2f78e625
Revises: 00051fd19c96
Create Date: 2026-08-06 13:42:31.802845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3cf2f78e625'
down_revision: Union[str, Sequence[str], None] = '00051fd19c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_accounts', 'provider_subject_id', new_column_name='provider_user_id')
    op.add_column('oauth_accounts', sa.Column('scopes', sa.String(), nullable=True))
    op.add_column('oauth_accounts', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_oauth_accounts_provider_subject_id', table_name='oauth_accounts')
    op.create_index(op.f('ix_oauth_accounts_provider_user_id'), 'oauth_accounts', ['provider_user_id'], unique=False)
    
    op.alter_column('users', 'name', new_column_name='full_name')
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name', new_column_name='name')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'avatar_url')
    
    op.alter_column('oauth_accounts', 'provider_user_id', new_column_name='provider_subject_id')
    op.drop_index(op.f('ix_oauth_accounts_provider_user_id'), table_name='oauth_accounts')
    op.create_index('ix_oauth_accounts_provider_subject_id', 'oauth_accounts', ['provider_subject_id'], unique=False)
    op.drop_column('oauth_accounts', 'expires_at')
    op.drop_column('oauth_accounts', 'scopes')
    # ### end Alembic commands ###
