"""add_workspace_status

Revision ID: cc0e34527ce7
Revises: f71f3d45f2d8
Create Date: 2026-08-06 23:44:34.760166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0e34527ce7'
down_revision: Union[str, Sequence[str], None] = 'f71f3d45f2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ENUMs first
    plantier = postgresql.ENUM('FREE', 'PRO', 'ENTERPRISE', name='plantier')
    plantier.create(op.get_bind(), checkfirst=True)
    
    workspacestatus = postgresql.ENUM('ACTIVE', 'SUSPENDED', name='workspacestatus')
    workspacestatus.create(op.get_bind(), checkfirst=True)
    
    # Add columns
    # op.add_column('subscriptions', sa.Column('plan', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='plantier'), server_default='FREE', nullable=False))
    # op.add_column('workspace_members', sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'DEVELOPER', 'SUPPORT', 'VIEWER', name='memberrole'), server_default='VIEWER', nullable=False))
    # op.add_column('workspaces', sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='workspacestatus'), server_default='ACTIVE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('workspaces', 'status')
    # op.drop_column('workspace_members', 'role')
    # op.drop_column('subscriptions', 'plan')
    # ### end Alembic commands ###
