"""Add indexing metrics to RepoIndexJob

Revision ID: e2362bc6b383
Revises: b02c94ec8ada
Create Date: 2026-08-20 21:46:36.132097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2362bc6b383'
down_revision: Union[str, Sequence[str], None] = 'b02c94ec8ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_index_jobs', sa.Column('files_skipped', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('repo_index_jobs', sa.Column('bytes_processed', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('repo_index_jobs', sa.Column('budget_limit', sa.BigInteger(), nullable=True))
    op.add_column('repo_index_jobs', sa.Column('budget_exceeded', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('repo_index_jobs', sa.Column('truncation_reason', sa.String(), nullable=True))
    op.add_column('repo_index_jobs', sa.Column('estimated_vector_storage', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('repo_index_jobs', sa.Column('estimated_payload_storage', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('repo_index_jobs', sa.Column('estimated_index_overhead_bytes', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('repo_index_jobs', sa.Column('estimated_total_semantic_storage', sa.BigInteger(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_index_jobs', 'estimated_total_semantic_storage')
    op.drop_column('repo_index_jobs', 'estimated_index_overhead_bytes')
    op.drop_column('repo_index_jobs', 'estimated_payload_storage')
    op.drop_column('repo_index_jobs', 'estimated_vector_storage')
    op.drop_column('repo_index_jobs', 'truncation_reason')
    op.drop_column('repo_index_jobs', 'budget_exceeded')
    op.drop_column('repo_index_jobs', 'budget_limit')
    op.drop_column('repo_index_jobs', 'bytes_processed')
    op.drop_column('repo_index_jobs', 'files_skipped')
    # ### end Alembic commands ###
