"""Add ActivityLog extension

Revision ID: e46924abc379
Revises: 732c1c6ed714
Create Date: 2026-08-27 18:57:23.280368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e46924abc379'
down_revision: Union[str, Sequence[str], None] = '732c1c6ed714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('activity_logs', sa.Column('bug_id', sa.UUID(), nullable=True))
    op.add_column('activity_logs', sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_activity_logs_bug_id'), 'activity_logs', ['bug_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_organization_id'), 'activity_logs', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'activity_logs', 'bugs', ['bug_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activity_logs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_index(op.f('ix_activity_logs_organization_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_bug_id'), table_name='activity_logs')
    op.drop_column('activity_logs', 'metadata_payload')
    op.drop_column('activity_logs', 'bug_id')
    op.drop_column('activity_logs', 'organization_id')
    # ### end Alembic commands ###
