"""enforce_one_workspace_per_organization

Revision ID: ea36ca21aa2b
Revises: 8e1427331d35
Create Date: 2026-08-28 11:24:41.841560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea36ca21aa2b'
down_revision: Union[str, Sequence[str], None] = '8e1427331d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workspaces_organization_id', table_name='workspaces')
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.create_index('ix_workspaces_organization_id', 'workspaces', ['organization_id'], unique=False)
    # ### end Alembic commands ###
