"""update_repository_intelligence

Revision ID: fa077bb892d5
Revises: a3a21c4f64a9
Create Date: 2026-08-18 16:21:12.399951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa077bb892d5'
down_revision: Union[str, Sequence[str], None] = 'a3a21c4f64a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_index_jobs', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.add_column('repo_index_jobs', sa.Column('model_version', sa.String(), nullable=True))
    op.add_column('repo_index_jobs', sa.Column('symbols_processed', sa.Integer(), nullable=False))
    op.add_column('repo_index_jobs', sa.Column('vectors_generated', sa.Integer(), nullable=False))
    op.add_column('repo_index_jobs', sa.Column('error_code', sa.String(), nullable=True))
    op.add_column('repo_index_jobs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('repo_index_jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('repo_index_jobs', sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_repo_index_jobs_organization_id'), 'repo_index_jobs', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'repo_index_jobs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('repositories', sa.Column('embedding_model', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('index_version', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('repository_size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'repository_size_bytes')
    op.drop_column('repositories', 'index_version')
    op.drop_column('repositories', 'embedding_model')
    op.drop_constraint(None, 'repo_index_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_repo_index_jobs_organization_id'), table_name='repo_index_jobs')
    op.drop_column('repo_index_jobs', 'failed_at')
    op.drop_column('repo_index_jobs', 'completed_at')
    op.drop_column('repo_index_jobs', 'duration_ms')
    op.drop_column('repo_index_jobs', 'error_code')
    op.drop_column('repo_index_jobs', 'vectors_generated')
    op.drop_column('repo_index_jobs', 'symbols_processed')
    op.drop_column('repo_index_jobs', 'model_version')
    op.drop_column('repo_index_jobs', 'organization_id')
    # ### end Alembic commands ###
