from pydantic import BaseModel, Field
from typing import List, Optional
import uuid

class AISearchRequest(BaseModel):
    query: str = Field(..., description="The semantic search query or question.")
    repository_id: Optional[uuid.UUID] = Field(None, description="Optional repository ID to limit search to a specific repository.")
    limit: int = Field(5, description="Number of context chunks to retrieve.", le=20)

class AIEvidence(BaseModel):
    file_reference: str = Field(..., description="The path of the file retrieved.")
    start_line: int = Field(..., description="Start line of the chunk.")
    end_line: int = Field(..., description="End line of the chunk.")
    score: float = Field(..., description="Relevance score (cosine similarity).")
    symbol_type: Optional[str] = Field(None, description="Type of symbol (e.g., function, class).")

class AISearchResponse(BaseModel):
    answer: str = Field(..., description="Grounded answer generated by the LLM.")
    evidence: List[AIEvidence] = Field(default_factory=list, description="Evidence chunks retrieved to answer the query.")
